### ISSUE TITLE
Bad documentation link

### ISSUE THREAD

**Issue by joa-quim** [markmbaum/BasicInterpolators.jl#3]
I've been beaten by this too. At a point the CI documentation decides to put-or-drop the docs in a different ``gh-pages`` directory.
This gives a 404
![image](https://user-images.githubusercontent.com/537321/134192257-487e17b7-5dc5-4705-b69d-fa84bc9f6771.png)

because it points to a non existent
https://markmbaum.github.io/BasicInterpolators.jl/stable

**Comment by markmbaum** [comment]
Thanks for letting me know. I just fixed the link.
