### ISSUE TITLE
multithreading or GPU support?

### ISSUE THREAD

**Issue by honghuzi** [markmbaum/BasicInterpolators.jl#4]
As the interpolation problem cost huge computation time when the scale of the target grid to interpolate increases, it would be very nice that the package support multithreading and GPU computing.
Is there any plan?

**Comment by markmbaum** [comment]
I have no plan to implement either inside the package right now. You can easily use an individual interpolator in parallel, though. For example, to accelerate a big batch of 1D interpolations you could do something like

```
using BasicInterpolators
using Base.Threads: @threads
using BenchmarkTools

x = LinRange(0, 1, 1_000_000)
y = @. x^2 - x + 1
p = CubicSplineInterpolator(x, y, NoBoundaries())

xi = LinRange(0, 1, 1_000_000)
yi = zeros(length(xi))

BenchmarkTools.@btime begin
    @threads for i ∈ eachindex($xi)
        @inbounds $yi[i] = $p($xi[i])
    end
end
```

which takes about 11 ms on my dinky computer. I turned off the interpolator boundary checks by using `NoBoundaries()` and turned off the vector index checks by using the `inbounds` macro. The interpolator's internal state is frozen, so it's fine to use it in parallel. This is true for all of them except the `BichebyshevInterpolator`, which is [not thread safe](https://markmbaum.github.io/BasicInterpolators.jl/dev/2d/#BasicInterpolators.BichebyshevInterpolator).

Does that help?
What's your application?

**Comment by markmbaum** [comment]
Which interpolator are you trying to speed up? Interpolation time for the `BilinearInterpolator` should scale reasonably well with grid size, logarithmically with the number of points on an axis. What's your application?

**Comment by markmbaum** [comment]
I have no plan to implement either inside the package right now, but I just made some updates (v0.7) to ensure that you can easily use an individual interpolator in parallel. For example, to accelerate a big batch of 1D interpolations you can do something like

```
using BasicInterpolators
using Base.Threads: @threads
using BenchmarkTools

x = LinRange(0, 1, 1_000_000)
y = @. x^2 - x + 1
p = CubicSplineInterpolator(x, y, NoBoundaries())

xi = LinRange(0, 1, 1_000_000)
yi = zeros(length(xi))

BenchmarkTools.@btime begin
    @threads for i ∈ eachindex($xi)
        @inbounds $yi[i] = $p($xi[i])
    end
end
```

which takes about 70 ms on my dinky computer. To speed it up a little, I turned off the interpolator boundary checks by using `NoBoundaries()` and turned off the vector index checks by using the `inbounds` macro. The interpolator's internal state is frozen, so it's fine to use it in parallel. This is true for all of them except the `BichebyshevInterpolator`, which is [not thread safe](https://markmbaum.github.io/BasicInterpolators.jl/dev/2d/#BasicInterpolators.BichebyshevInterpolator).

In general, the interpolation time will scale logarithmically with the number of nodes (`x`) and linearly with the number of samples (`xi`).

Does that help?

**Comment by honghuzi** [comment]
The feature I desire is the parallelization inside the package. Besides, the threaded version demo you just showed also works for BasicInterpolators v0.6.5. So I don't understand what the updates are that makes the parallelization easily.

**Comment by markmbaum** [comment]
the old version cached cell indices to speed up the search, which may work in threads but is dubious
